name: "Set up QEMU - Github Online Runner"
on:
  workflow_dispatch:

jobs:
  do-the-job:
    name: Do the job on the runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Build
        run: |
          docker buildx build --platform=linux/arm64  .
